version: '3.8'

services:
  backend:
    build: .
    container_name: django_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    restart: always
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongodb_data:
